# Generated by Django 4.2.18 on 2025-02-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_members_project_name_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_members',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
